version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:12
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Running linter
          command: yarn lint
      - run:
          name: Running unit tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Run cypress tests
          command: |
            yarn cypress run --reporter "./dist/index.js" --spec "$(circleci tests glob "./cypress/integration/**/*.spec.ts" | circleci tests split --split-by=timings | paste -sd "," -)"
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
